version: "3.9"

services:
  app-server:
    build: .
    ports:
      - "12857:12857"
    depends_on:
      - production-db
    command: yarn serve

  production-db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: a password for the database admin user
      POSTGRES_DB: ytdpnl
    ports:
      - 54321:5432
    volumes:
      - production-ytdpnl:/var/lib/postgresql/data

  development-db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: another password for the development database admin user
      POSTGRES_DB: ytdpnl
    ports:
      - 54322:5432
    volumes:
      - development-ytdpnl:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - "9180:8080"

volumes:

  production-ytdpnl:
    driver: local

  development-ytdpnl:
    driver: local
