#!/bin/env bash
echo "Generating crx file for extension..."
if google-chrome \
    --pack-extension=/home/djfm/projects/ytdpnl-extension/dist/chrome \
    --pack-extension-key=/home/djfm/.ssh/ytdpnl \
; then
    echo "Extension packed!"
else
    echo "Error packing extension :("
fi
